export const FETCH_USERINFO_REQ = 'FETCH_USERINFO_REQ';
export const FETCH_USERINFO_SUC = 'FETCH_USERINFO_SUC';
export const FETCH_USERINFO_FAI = 'FETCH_USERINFO_FAI';
export const FETCH_LESSONINFO_REQ = 'FETCH_LESSONINFO_REQ';
export const FETCH_LESSONINFO_SUC = 'FETCH_LESSONINFO_SUC';
export const FETCH_LESSONINFO_FAI = 'FETCH_LESSONINFO_FAI';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_CLASS = 'FETCH_CLASS';